[package]
name = "helloworld-uefi"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
uefi = { version = "0.29.0", features = ["alloc", "global_allocator", "panic_handler", "logger", "qemu"] }
# important: uefi-services was deprecated