cargo-features = ["per-package-target"]

[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"
default-target = "x86_64-unknown-uefi"

[dependencies]
hashbrown = "0.14.5"
uefi = { version = "0.29.0", features = ["alloc", "global_allocator", "panic_handler", "logger", "qemu"] }
