[package]
name = "builder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.11", features = ["derive"] }
gpt = "4.0.0-rc.3"
anyhow = "1.0.68"
env_logger = "0.11.5"
fatfs = "0.3.5"
fscommon = "0.1.1"
log = "0.4.17"
mbrman = "0.5.1"